language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="512"
    BYOND_MINOR="1463"
    DM_BUILDFILE="baystation12.dme"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

after_success:
  - chmod +x ./send-to-discord.sh
  - ./send-to-discord.sh success $WEBHOOK_URL

after_failure:
  - chmod +x ./send-to-discord.sh
  - ./send-to-discord.sh failure $WEBHOOK_URL

script:
  - (! grep 'step_[xy]' maps/**/*.dmm)
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh ${DM_BUILDFILE}

before_deploy:
  if ! [[ $TRAVIS_ZIPPED_ARCHIVE ]]; then
    export TRAVIS_ZIPPED_ARCHIVE="TRUE" &&
    zip -rq latest * &&
    mkdir -p dpl_cd_upload &&
    mv latest.zip dpl_cd_upload/latest.zip;
  fi

deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    branch: dev
  bucket: onyxbay.stage
  region: eu-west-3
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: onyxbay.stage
  key: latest.zip
  bundle_type: zip
  application: OnyxBayStage
  deployment_group: OnyxBayDeploymentGroup
  region: eu-west-3
  on: *2