name: Улучшение
description: Предложить идею по улучшению сборки.
labels:
  - "\U0001F535требуется проверка"
  - "\U0001F529 улучшение"
body:
  - type: textarea
    id: description
    attributes:
      label: Улучшение
      description: В чем смысл вашего улучшения? Какую проблему оно решает? Четко и понятно опишите в чем заключается проблема.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Решение
      description: Опишите ваше решение проблемы. Четко и понятно опишите как вы видите решение своей проблемы.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: (Опционально) Альтернативы
      description: Опишите альтернативы, о которых вы думали. Почему именно ваше решение является лучшим?
  - type: textarea
    id: additional_info
    attributes:
      label: (Опционально) Дополнительная информация
      description: Добавьте любую дополнительную информацию о вашей идее. Если у вас есть какие-то ресурсы - примеры внутриигрового текста, спрайты, картинки, звуки - обязательно прикрепите. Тогда шансов, что вашу идею реализуют, будет гораздо больше.
